name: CI

on:
  pull_request:
    branches: [master]

env:
  DEFAULT_PYTHON: 3.14

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Python modules
        run: |
          pip install --constraint=.github/workflows/constraints.txt pre-commit black flake8 reorder-python-imports

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  pytest:
    runs-on: "ubuntu-latest"
    name: Pytest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3"

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install dependencies
        run: |
          pip install --constraint=.github/workflows/constraints.txt -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov pytest-homeassistant-custom-component

      - name: Run pytest
        run: |
          pytest tests/ -v --cov=custom_components.integration_ecowitt --cov-report=xml

      - name: Write coverage in pull request comment
        uses: "paambaati/codeclimate-action@v3.0.3"
        with:
          coverageCommand: "echo 'Skipping coverage generation'"
          coverageLocations: "./coverage.xml"
          githubToken: "${{ secrets.GITHUB_TOKEN }}"
